name: CI Workflow

on:
  push:
    branches:
        #trigger on pushes to main branch
      - main
  pull_request:
    branches:
        #trigger on pull requests targeting main branch
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '20.19'

      - name: Install frontend dependencies
        run: |
          cd Task_Flow_AI_Analytics/frontend
          npm install

      - name: Run frontend lint
        run: |
            cd Task_Flow_AI_Analytics/frontend
            npm run lint

      - name: Build frontend with Vite
        run: |
          cd Task_Flow_AI_Analytics/frontend
          npm run build 

